stages:
  - build
  - test

build_image:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t api .
    - docker run -d -p 3000:3000 --name my_container api npm start
    - sleep 20
    - docker exec my_container npm test
  after_script:
    - docker stop my_container
