stages:
  - install
  - start
  - test

install_dependencies:
  stage: install
  script:
    - npm install

start_app:
  stage: start
  script:
    - npm run start

run_tests:
  stage: test
  script:
    - npm test
