stages:
  - cleanup
  - build
  - test

cleanup_build:
  stage: cleanup
  image: docker:latest
  script:
    - docker rm -f sae || true

build_image:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t api .
  artifacts:
    paths:
      - api.tar
  rules:
    - exists:
        - api.tar

test_image:
  stage: test
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker load -i api.tar
    - docker run -d -p 3000:3000 --name sae api npm start
    - sleep 20
    - docker exec sae npm test
  after_script:
    - docker stop sae

