stages:
  - cleanup
  - build
  - prepare_artifact
  - test
  - debug

cleanup_build:
  stage: cleanup
  script:
    - docker rm -f sae || true
    - rm -f api.tar || true

build_image:
  stage: build
  image: docker:latest
  services:
    - name: docker:dind
    - name: alpine/git
  script:
    - apk --update add git
    - docker build -t api .
    - ls -la

prepare_artifact:
  stage: prepare_artifact
  script:
    - tar -cvf api.tar .

test_image:
  stage: test
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker run -d -p 3000:3000 --name sae api npm start
    - sleep 20
    - docker exec sae npm test
  after_script:
    - docker stop sae
  artifacts:
    paths:
      - api.tar

debug:
  stage: debug
  script:
    - ls -la
