stages:
  - cleanup
  - build
  - test

cleanup_build:
  stage: cleanup
  image: docker:latest
  script:
    - docker rm -f sae || true
    - rm -f api.tar || true

build_image:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t api .
    - ls
  artifacts:
    paths:
      - api.tar


test_image:
  stage: test
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker run -d -p 3000:3000 --name sae api npm start
    - sleep 20
    - docker exec sae npm test
  after_script:
    - docker stop sae
