stages:
  - cleanup
  - build
  - test
  - debug  # Ajout de l'étape de débogage

cleanup_build:
  stage: cleanup
  image: docker:latest
  script:
    - docker rm -f sae || true
    - rm -f api.tar || true

build_image:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t api .
    - ls  # Ajout de cette commande pour vérifier le contenu du répertoire de travail
  artifacts:
    paths:
      - api.tar

test_image:
  stage: test
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker run -d -p 3000:3000 --name sae api npm start
    - sleep 20
    - docker exec sae npm test
  after_script:
    - docker stop sae

debug:
  stage: debug
  script:
    - ls -la  # Vérifiez le contenu du répertoire de travail
