stages:
  - build
  - test

build_image:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t api .
    - docker run -d -p 3000:3000 api npm start
    - sleep 20
    - docker exec $(docker ps -q) npm run test
  after_script:
    - docker stop $(docker ps -q)
